### PR TITLE
chore: Upgrade AGP from 7.6 to 8.0 + Java, Kotlin & Compose

### PR DESCRIPTION
**Pull request by ManonPolle**
## Context
Related to https://github.com/Decathlon/vitamin-compose/issues/146
 
| Version | Previous | New |
|--------|--------|--------|
| Java | 11 | 17 |
| AGP | 7.4.0 | 8.0.1 |
| Gradle wrapper | 7.0.2 | 8.1.1 | 
| Kotlin Gradle Plugin | 1.7.20 | 1.8.21 |
|Compose compiler|1.3.2|1.4.7|
|Compose ui |1.3.2|1.3.3|
|Compose material |1.3.1|1.3.1|

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on a phone device/emulator.
- [ ] I have tested on a tablet device/emulator.
- [ ] I have tested on a large screen device/emulator.

## Does this introduce a breaking change?

- Yes
- No

### CODE REVIEW

**Comment by dktbitrise** [comment]
### You can download the apk here :

**Comment by dktbitrise** [comment]
### You can download the apk here :

**Comment by dktbitrise** [comment]
### You can download the apk here :

**Comment by dktbitrise** [comment]
### You can download the apk here :

**Comment by dktbitrise** [comment]
### You can download the apk here :

**Comment by dktbitrise** [comment]
### You can download the apk here :

**Comment by dktbitrise** [comment]
### You can download the apk here :

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/3993485b-28e3-44ba-9794-03c2aecedf7b/artifact/f85f983d3a6f0983/p/7dfe7056d4a88defadf53ab860df9464

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/e1f9b64b-e538-47bd-ac78-33163b6a0b46/artifact/69f0183a17cb4b7d/p/420bc49f8b7e9b22675a922754eb09bc

**Review by apauchet — APPROVED** [review]

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/1276921f-b8c2-40f8-beb0-dfabb22a121b/artifact/c41713fe5bbff365/p/cea871ac691faa9f30d4541fe10d00b8

**Pull request merged**
