### PR TITLE
fix(Button): remove small button size

### PR DESCRIPTION
**Pull request by FDELAHA24**
## Changes description 🧑‍💻

Remove the small button size as requested in the issue

## Context 🤔

[34](https://github.com/Decathlon/vitamin-compose/issues/34)

## Checklist ✅

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check compose contract convention. It must follow conventions described [here](/CONVENTIONS.md).
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on a phone device/emulator.
- [x] I have tested on a tablet device/emulator.
- [x] I have tested on a large screen device/emulator.
- [ ] If it includes design changes, please ask for a review with a core team designer.

### CODE REVIEW

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/c8b4e2f6-f247-495d-bf41-e4ad7309e015/artifact/a69c86727286eee1/p/7a289d083bb777835cb4a1ed391e3da7

**Review by ManonPolle — DISMISSED** [review]

**Review by GerardPaligot — CHANGES_REQUESTED** [review]
Can you remove screenshots with small variants too?

**Comment by dktbitrise** [comment]
### You can download the apk here :

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/de08b400-4d08-42a6-90d3-ce81bc3a09d5/artifact/b389d9b07bbe1930/p/610600294227b270be5e6fbf8006c08d

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/117f8b85-237c-4f81-b0a4-db797f8fa33b/artifact/3c152651cb50ce8b/p/71f2be64bfeb62db4be00785e1c79437

**Review by GerardPaligot — APPROVED** [review]

**Pull request merged**
