### PR TITLE
chore(switches): add paparazzi tests

### LINKED ISSUE #95: test(switch): Add paparazzi tests
**Describe the solution you'd like**
Write tests with paparazzi for switch component for all variants & themes. 

**Additional context**
FYI Buttons already have ones.

### PR DESCRIPTION
**Pull request by FDELAHA24**
## Changes description 🧑‍💻

Add paparazzi tests

## Context 🤔

Closes #95 
Resolves https://github.com/Decathlon/vitamin-compose/issues/147
## Checklist ✅

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check compose contract convention. It must follow conventions described [here](/CONVENTIONS.md).
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [ ] I have tested on a phone device/emulator.
- [ ] I have tested on a tablet device/emulator.
- [ ] I have tested on a large screen device/emulator.
- [ ] If it includes design changes, please ask for a review `design-system-core-team-design` GitHub team.

### CODE REVIEW

**Review by corentin-stamper — DISMISSED** [review]

**Comment by dktbitrise** [comment]
### You can download the apk here :

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/abd6932b-739b-483d-8519-d9783a38fdd8/artifact/a9b318b0288603ee/p/9429124f56ebc0d32014a3c1d94fc343

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/560a2326-4e3d-4fe8-bb7e-df2aeadb7ad8/artifact/0749572cc590af64/p/fa0647c8e212b3c8f88c38385638df61

**Review by GerardPaligot — CHANGES_REQUESTED** [review]
After an internal discussion with @SimonLeclercq, the thumb in dark mode shouldn't be dark like that.
Tracking issue: https://github.com/Decathlon/vitamin-design/issues/216

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/bb02888d-ab16-4ae0-820d-4e8c3390ddc9/artifact/ccc6ab46c5080061/p/50437091d30f4d3ff60e9eb7b648b3fa

**Review by corentin-stamper — DISMISSED** [review]

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/3f5f0de5-4d56-4222-b981-654b8e3f1984/artifact/1b81c33e6944ccc5/p/034321b6ea5e2cbedf4e4e50de0a9c4e

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/e6286a67-2e82-486d-988f-e16b15863b5e/artifact/6cd8365fb667b0a3/p/766fe6e4df5db60f10cd3b1155bf8efe

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/a11d692d-a7b8-4f97-9a2f-c2b399204bc6/artifact/ef04407792fdfe3f/p/9c0aad964beccd9e9f00793b66a219e3

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/9e2f522c-7346-484b-a683-7d0811cd7559/artifact/558a2987f87d7b46/p/d692cc1dc661c3744cf639704c005a01

**Review by GerardPaligot — APPROVED** [review]

**Pull request merged**
