### PR TITLE
feat(Progress): Add extra small size

### PR DESCRIPTION
**Pull request by FDELAHA24**
## Changes description 🧑‍💻

Add extra small size for progress component

## Context 🤔

[#52](https://github.com/Decathlon/vitamin-compose/issues/52)

## Checklist ✅

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check compose contract convention. It must follow conventions described [here](/CONVENTIONS.md).
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on a phone device/emulator.
- [ ] I have tested on a tablet device/emulator.
- [ ] I have tested on a large screen device/emulator.
- [ ] If it includes design changes, please ask for a review `design-system-core-team-design` GitHub team.

## Screenshots 📸

Screenshot_20230106_154448

### CODE REVIEW

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/cd1b99af-656c-4db4-abe7-6d971878a700/artifact/8ca16865d9774c27/p/650115d7b9267ca07c08bc86431b7682

**Review by corentin-stamper — DISMISSED** [review]

**Comment by corentin-stamper** [comment]
@SimonLeclercq - Design validation needed

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/5d6b04c8-ebb6-431c-ad65-e83368b46c79/artifact/5ac0464013767e0c/p/6dc05d7d6f59431e7b893d86a9bf3009

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/811c4736-d2ad-4010-b5a7-c04de675cb88/artifact/bb2a66e5838b1c8a/p/69e82dcd1dd858c2b29e30a6202c0777

**Review by corentin-stamper — APPROVED** [review]

**Comment by SimonLeclercq** [comment]
👍

**Review by SimonLeclercq — APPROVED** [review]

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/95ea00a0-77ff-4035-8bb5-a30c8dfda2eb/artifact/cb5306dc48819004/p/20ecafb17846cea2b73baec374d8812e

**Pull request merged**
