### PR TITLE
fix(text-inputs): Character counter position

### PR DESCRIPTION
**Pull request by apauchet**
## Changes description 🧑‍💻

Fix issue about character counter position in cas of null helperText
Add textInput sample to check the fix 

## Context 🤔

Closes https://github.com/Decathlon/vitamin-android/issues/183

## Checklist ✅

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [X] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [X] Check compose contract convention. It must follow conventions described [here](/CONVENTIONS.md).
- [X] Check your code additions will fail neither code linting checks.
- [X] I have reviewed the submitted code.
- [X] I have tested on a phone device/emulator.
- [ ] I have tested on a tablet device/emulator.
- [ ] I have tested on a large screen device/emulator.
- [ ] If it includes design changes, please ask for a review `design-system-core-team-design` GitHub team.

## Screenshots 📸

Screenshot_20230721_151620

### CODE REVIEW

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/15c6893b-9eed-4337-b7f9-336f05dda659/artifact/9ec6148419c85107/p/e2e14cf57ced1f610b0df5bb05e3ee4e

**Review by FDELAHA24 — CHANGES_REQUESTED** [review]
Maybe we could add the case (counter wihtout helper text) into `VitaminTextInputsPrimaryTest` and regenerate the snapshot ?

**Comment by dktbitrise** [comment]
### You can download the apk here :

**Review by ManonPolle — APPROVED** [review]

**Review by FDELAHA24 — APPROVED** [review]

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/5ee41acd-6ff0-4693-bfa1-d2dcfa8777cd/artifact/bb8371037c9a5380/p/e7f25bffa3c41ce774fd6572971b2b05

**Pull request merged**
